server:
  port: 30007
spring:
  application:
    name: admin-server
  security:

    user:
      name: inkbox
      password: inkbox
  boot:
    admin:
      context-path: admin-server
#      ui:
#        extension-resource-locations: file:/Users/apple/resource/temp/spring-boot-admin/spring-boot-admin-samples/spring-boot-admin-sample-custom-ui/target/dist/
#        cache:
#          no-cache: true
#        cache-templates: false

eureka:
  client:
    service-url:
      defaultZone: http://192.168.3.72:3098/eureka/
#    register-with-eureka: false

# admin是个拉模型，在把自己注册之后再启用security就必须注入认证信息
  instance:
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}