server:
  port: 30002
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: test
#          uri: lb://eureka
#          predicates:
#            - Host=yapi.bcyunqian.com,www.bcyunqian.com
#            - Path=/PP/***
#          filters:
#            - PreserveHostHeader
#            - StripPrefix=1
#            - RewritePath=/foo/(?<segment>.*), /$\{segment}

  profiles:
    active: dev
  redis:
    host: 192.168.3.64
    port: 6379
    database: 12
#  boot:
#    admin:
#      client:
#        api-path: instances-server
eureka:
  client:
    service-url:
      defaultZone: http://192.168.3.72:3098/eureka/
    eureka-service-url-poll-interval-seconds: 3
    registry-fetch-interval-seconds: 3
  instance:
    metadata-map:
      management:
        port: ${management.server.port}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  server:
    port: 9698 # 不会生效

logging:
  level:
    cn.inkroom: debug
    org:
      apache.http: off
      springframework:
        cloud:
          gateway:
            handler:
              RoutePredicateHandlerMapping: debug
              FilteringWebHandler: debug

    javax: off
    sun: off
    com:
      netflix:
        discovery:
          shared: off

