server:
  port: 30002
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: test
#          uri: lb://eureka
#          predicates:
#            - Host=yapi.bcyunqian.com,www.bcyunqian.com
#            - Path=/PP/***
#          filters:
#            - PreserveHostHeader
#            - StripPrefix=1
#            - RewritePath=/foo/(?<segment>.*), /$\{segment}

  profiles:
    active: dev
  redis:
    host: 127.0.0.1
    port: 6399
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:3098/eureka/
    eureka-service-url-poll-interval-seconds: 3
    registry-fetch-interval-seconds: 3
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  level:
    cn.inkroom: debug
    org:
      apache.http: off
      springframework:
        cloud:
          gateway:
            handler:
              RoutePredicateHandlerMapping: debug
              FilteringWebHandler: debug

    javax: off
    sun: off
    com:
      netflix:
        discovery:
          shared: off

