server:
  port: 30001
spring:
  application:
    name: zuul
  zipkin:
    # 服务发现有问题，暂时只能使用url
#    discovery-client-enabled: true
    base-url: http://localhost:30005
  sleuth:
    sampler:
      probability: 1.0
      rate: 30
  cloud:
    discovery-client-enabled: true
      service:
        name: zipkin
    nacos:
      discovery:
        server-addr: 127.0.0.1:9092
        username: nacos
        password: nacos
eureka:
  client:
    service-url:
      defaultZone: http://192.168.3.72:3098/eureka/


zuul:
  routes:
    user:
      path: /u/**
      server-id: user
    fund:
      path: /f/**
      server-id: fund
    product:
      path: /p/**
      server-id: product
    zipkin:
      path: /zipkin/**
      server-id: zipkin
logging:
  level:
    cn.inkroom: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'