server:
  port: 30001
spring:
  application:
    name: zuul
  zipkin:
    # 服务发现有问题，暂时只能使用url
#    discovery-client-enabled: true
    base-url: http://localhost:30005
  sleuth:
    sampler:
      probability: 1.0
      rate: 30
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:3098/eureka/

zuul:
  routes:
    user:
      path: /u/**
      server-id: user
    fund:
      path: /f/**
      server-id: fund
    product:
      path: /p/**
      server-id: product
    zipkin:
      path: /zipkin/**
      server-id: zipkin
logging:
  level:
    cn.inkroom: debug