server:
  port: 30003
spring:
  application:
    name: config
  cloud:
    config:
      server:
#        git:
#          uri: https://github.com/inkroom/springBoot-cloud
#          basedir: config
          native:
            search-locations: /home/ink/study/study/后端/workplace/github/springBoot-cloud/config

  profiles:
    active: native #使用非git存储，都需要注明该配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:3098/eureka/