server:
  port: 30003
spring:
  application:
    name: config
  cloud:
    config:
      server:
#        git:
#          uri: https://github.com/inkroom/springBoot-cloud
#          basedir: config
          native:
            search-locations: /Users/apple/resource/project/java/SpringCloud/config

  profiles:
    active: native #使用非git存储，都需要注明该配置
eureka:
  client:
    service-url:
      defaultZone: http://192.168.3.72:3098/eureka/